### ISSUE TITLE
SkewTPlus fails with current matplotlib 

### ISSUE THREAD

**Issue by mhaberler** [aperezhortal/SkewTplus#9]
running an example:

`````
$ python soundingFromWeb.py
/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/SkewTplus-1.1.2-py3.8-macosx-10.9-x86_64.egg/SkewTplus/skewT.py:88: MatplotlibDeprecationWarning:
The 'label' parameter of __init__() was deprecated in Matplotlib 3.3 and will be removed two minor releases later. If any parameter follows 'label', they should be passed as keyword, not positionally.
  return SkewXTick(self.axes, 0, '', major=major)
/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/SkewTplus-1.1.2-py3.8-macosx-10.9-x86_64.egg/SkewTplus/skewT.py:88: MatplotlibDeprecationWarning:
The 'label' parameter of __init__() was deprecated in Matplotlib 3.3 and will be removed two minor releases later. If any parameter follows 'label', they should be passed as keyword, not positionally.
  return SkewXTick(self.axes, 0, '', major=major)
Traceback (most recent call last):
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/backends/backend_macosx.py", line 61, in _draw
    self.figure.draw(renderer)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/figure.py", line 1863, in draw
    mimage._draw_list_compositing_images(
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 411, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 2747, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/axis.py", line 1169, in draw
    tick.draw(renderer)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/SkewTplus-1.1.2-py3.8-macosx-10.9-x86_64.egg/SkewTplus/skewT.py", line 58, in draw
    if self.gridOn and transforms.interval_contains(
AttributeError: 'SkewXTick' object has no attribute 'gridOn'
/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/SkewTplus-1.1.2-py3.8-macosx-10.9-x86_64.egg/SkewTplus/skewT.py:88: MatplotlibDeprecationWarning:
The 'label' parameter of __init__() was deprecated in Matplotlib 3.3 and will be removed two minor releases later. If any parameter follows 'label', they should be passed as keyword, not positionally.
  return SkewXTick(self.axes, 0, '', major=major)
Traceback (most recent call last):
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/backends/backend_macosx.py", line 61, in _draw
    self.figure.draw(renderer)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/figure.py", line 1863, in draw
    mimage._draw_list_compositing_images(
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 411, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 2747, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/axis.py", line 1169, in draw
    tick.draw(renderer)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/SkewTplus-1.1.2-py3.8-macosx-10.9-x86_64.egg/SkewTplus/skewT.py", line 58, in draw
    if self.gridOn and transforms.interval_contains(
AttributeError: 'SkewXTick' object has no attribute 'gridOn'
````

do you have any suggestions how to fix this?

it'd be a pity if the package became unusable due to matplotlib changes

**Comment by aperezhortal** [comment]
Hi @mhaberler, I'll take a look at it. I think that `self.gridOn` should be replaced by `self._gridOn`, but I'm not 100% sure. An old version of the [Metpy's skewt class](https://github.com/Unidata/MetPy/blob/063d5b5bb7bc356b8d0761e0cccd9adf1b39783b/metpy/plots/skewt.py) used the underscored attribute.

**Comment by mhaberler** [comment]
that alone does not cut it.

````
(dev-3.8) BigMac-645:examples mah$ python soundingFromWeb.py
/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/SkewTplus-1.1.2-py3.8-macosx-10.9-x86_64.egg/SkewTplus/skewT.py:88: MatplotlibDeprecationWarning:
The 'label' parameter of __init__() was deprecated in Matplotlib 3.3 and will be removed two minor releases later. If any parameter follows 'label', they should be passed as keyword, not positionally.
  return SkewXTick(self.axes, 0, '', major=major)
/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/SkewTplus-1.1.2-py3.8-macosx-10.9-x86_64.egg/SkewTplus/skewT.py:88: MatplotlibDeprecationWarning:
The 'label' parameter of __init__() was deprecated in Matplotlib 3.3 and will be removed two minor releases later. If any parameter follows 'label', they should be passed as keyword, not positionally.
  return SkewXTick(self.axes, 0, '', major=major)
Traceback (most recent call last):
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/backends/backend_macosx.py", line 61, in _draw
    self.figure.draw(renderer)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/figure.py", line 1863, in draw
    mimage._draw_list_compositing_images(
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 411, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 2747, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/axis.py", line 1169, in draw
    tick.draw(renderer)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/SkewTplus-1.1.2-py3.8-macosx-10.9-x86_64.egg/SkewTplus/skewT.py", line 58, in draw
    if self._gridOn and transforms.interval_contains(
AttributeError: 'SkewXTick' object has no attribute '_gridOn'
/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/SkewTplus-1.1.2-py3.8-macosx-10.9-x86_64.egg/SkewTplus/skewT.py:88: MatplotlibDeprecationWarning:
The 'label' parameter of __init__() was deprecated in Matplotlib 3.3 and will be removed two minor releases later. If any parameter follows 'label', they should be passed as keyword, not positionally.
  return SkewXTick(self.axes, 0, '', major=major)
Traceback (most recent call last):
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/backends/backend_macosx.py", line 61, in _draw
    self.figure.draw(renderer)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/figure.py", line 1863, in draw
    mimage._draw_list_compositing_images(
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 411, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 2747, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/matplotlib/axis.py", line 1169, in draw
    tick.draw(renderer)
  File "/Users/mah/opt/miniconda3/envs/dev-3.8/lib/python3.8/site-packages/SkewTplus-1.1.2-py3.8-macosx-10.9-x86_64.egg/SkewTplus/skewT.py", line 58, in draw
    if self._gridOn and transforms.interval_contains(
AttributeError: 'SkewXTick' object has no attribute '_gridOn'
````

**Comment by aperezhortal** [comment]
Hi @mhaberler, 
I opened a PR updating the package for matplolib>=3.1 (see PR #10).
I will do a little bit more testing, and then I will merge it. Feel free to try the [fixes](https://github.com/aperezhortal/SkewTplus/tree/fixes) branch to double-check that the error was fixed.

**Comment by mhaberler** [comment]
oh boy, that became a tad bigger than I thought! thanks for taking the time, appreciated!
